"""add score 

Revision ID: 1668e8a3509e
Revises: 8a70e33266ef
Create Date: 2025-01-24 16:15:06.599235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1668e8a3509e'
down_revision = '8a70e33266ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entreprise_reglementation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entreprise_reglementation', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
