"""applicable te conforme nullable

Revision ID: 305c3c09c4a8
Revises: 1668e8a3509e
Create Date: 2025-01-24 17:18:14.575438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305c3c09c4a8'
down_revision = '1668e8a3509e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('applicable',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('conforme',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('conforme',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
        batch_op.alter_column('applicable',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
