"""tester uuid

Revision ID: 31892a1711e6
Revises: 305c3c09c4a8
Create Date: 2025-01-24 23:22:47.864453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31892a1711e6'
down_revision = '305c3c09c4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
