"""ajout lange reglemntation et supprimer de l'artle

Revision ID: 356fa8ad4129
Revises: c1b8f9d85816
Create Date: 2025-01-23 10:11:52.864540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356fa8ad4129'
down_revision = 'c1b8f9d85816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('uq_article_titre', type_='unique')
        batch_op.drop_column('titre')
        batch_op.drop_column('langue')

    with op.batch_alter_table('reglementation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('langue', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglementation', schema=None) as batch_op:
        batch_op.drop_column('langue')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('langue', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('titre', sa.VARCHAR(length=200), nullable=False))
        batch_op.create_unique_constraint('uq_article_titre', ['titre'])

    # ### end Alembic commands ###
