"""ajout titre du paragraphe article

Revision ID: 751fdee4ad99
Revises: 356fa8ad4129
Create Date: 2025-01-23 11:02:56.297315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751fdee4ad99'
down_revision = '356fa8ad4129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titre', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('titre')

    # ### end Alembic commands ###
