"""ajout date creation entreprise

Revision ID: c1b8f9d85816
Revises: 56f4b2191e22
Create Date: 2025-01-22 16:53:34.101186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b8f9d85816'
down_revision = '56f4b2191e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entreprise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entreprise', schema=None) as batch_op:
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###
